add missing label selector
homedepot/go-clouddriver pull request #25
Opened 2021-04-01 17:14 UTC by yasmin-abdullah

Add unused MatchExpressions in Deploy Manifest.

[story](https://www.pivotaltracker.com/story/show/177144386)

2021-04-01 17:32 UTC, billiford commented
A couple things just to verify before we merge...

1) What is the output of `ls.String()`?

2) Find some kubernetes resources that match a given label selector defined in step 1 - verify that it is only returning resources that do not have an empty `moniker.spinnaker.io/sequence` label.

For step 2 use both `kubectl` and a `main.go` file that filters results to verify this is working as intended. See [this comment](https://github.com/homedepot/go-clouddriver/pull/3#issuecomment-742037259) for help creating a working selector for kubectl that limits the response.

2021-04-05 20:02 UTC, yasmin-abdullah commented
2. This is a list of all the config maps that do and don't have the sequence label 

```yaml
$ kubectl -n spinnaker get cm artifacts-config -o yaml
apiVersion: v1
data:
  no-auth-http-file.json: |-
    {
      "name": "no-auth-http-account",
      "types": [
        "http/file"
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: cd-go-clouddriver
  name: artifacts-config
  namespace: spinnaker
```
The output for a versined config where the label `moniker.spinnaker.io/sequence` exists
``` yaml
$ kubectl -n spinnaker get cm artifacts-config-v000 -o yaml
apiVersion: v1
data:
  no-auth-http-file.json: |-
    {
      "name": "no-auth-http-account",
      "types": [
        "http/file"
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: cd-go-clouddriver
    moniker.spinnaker.io/sequence: "0"
  name: artifacts-config-v000
  namespace: spinnaker
```

2021-04-05 20:18 UTC, billiford requested changes

2021-04-05 20:18 UTC, billiford commented on pkg/http/core/kubernetes/deploy.go
> +	ls, err := metav1.LabelSelectorAsSelector(&labelSelector)
Add a check for this error.

2021-04-05 20:18 UTC, billiford commented on pkg/http/core/kubernetes/deploy.go
> +func getListOptions(u *unstructured.Unstructured, app string) (lo metav1.ListOptions, err error) {
Remove the return declarations.

2021-04-05 20:18 UTC, billiford commented on pkg/http/core/kubernetes/deploy_test.go
> +
Remove this comment.

2021-04-05 20:18 UTC, billiford commented on pkg/http/core/kubernetes/deploy_test.go
> +				// Expect(len(results.Items)).To(Equal(1))
Remove these comments.

2021-04-05 21:18 UTC, billiford approved these changes

2021-04-05 21:18 UTC, merged