Adds GET/PUT operations for kubernetes providers
homedepot/go-clouddriver pull request #36
Opened 2021-04-28 12:16 UTC by dmrogers7

This implements two new paths for kubernetes providers
- `GET /v1/kubernetes/providers/:name` which returns the kubernetes provider, with read/write permissions
- `PUT /vi/kubernetes/providers` which
   - creates the provider and permissions when the provider does not already exist
   - replaces the provider and permissions when the provider already exists
   
This also refactors the create read/write permissions functions, moving them out of `providers.go` and encapsulating them inside the create kubernetes provider function in `sql.go`, which follows the pattern done with delete permissions.

2021-04-28 16:44 UTC, billiford requested changes

2021-04-28 16:44 UTC, billiford commented on pkg/sql/sql.go
> +// Connaction returns the driver and connection string to the DB.
Connection*

2021-04-28 16:44 UTC, billiford commented on pkg/http/v1/provider.go
> +}
Add test coverage for this function.

2021-04-28 16:44 UTC, billiford commented on pkg/http/v1/provider.go
> +}
Add test coverage for this function.

2021-04-28 16:44 UTC, billiford commented
Thanks for moving the logic to create a provider's read permissions to the `sql` package. The `godoc` comments look great!

2021-04-29 10:48 UTC, dmrogers7 commented on pkg/http/v1/provider.go
> +}
Done

2021-04-29 10:48 UTC, dmrogers7 commented on pkg/http/v1/provider.go
> +}
Done

2021-04-29 13:43 UTC, billiford approved these changes

2021-04-29 13:43 UTC, merged