add support for max version history
homedepot/go-clouddriver pull request #68
Opened 2021-09-29 00:07 UTC by billiford

- add support for annotation `strategy.spinnaker.io/max-version-history`

2021-09-29 10:01 UTC, dmrogers7 requested changes

2021-09-29 10:01 UTC, dmrogers7 commented on pkg/kubernetes/strategy.go
> +// MaxVersionHistory returns true if the value of the annotation
I messed up the original comment (too much copy/paste) - should be
```go
// MaxVersionHistory returns the value as an int of the annotation
```

2021-09-30 19:24 UTC, billiford commented
Merged with the changes for namespace-scoped accounts and fixed the comment verbiage. Do we want a test case that shows max version history uses the provider's namespace?

2021-09-30 19:50 UTC, dmrogers7 approved these changes

2021-09-30 19:50 UTC, merged